#[[redirects]]
#  from = "/*"
#  to = "/offline"
#  status = 503
#  force = true
#
#[[redirects]]
#  from = "/*"
#  to = "/cachereset"
#  status = 503
#  force = true

[[redirects]]
  from = "/"
  to = "/#"
  status = 303
  force = false

[[redirects]]
from = "/afiles/other_logos/ia-logo-150x150.png"
to = "/afiles/sf2a/other_logos/loader.gif"
status = 303
force = false

[[redirects]]
from = "/apache.conf"
to = "/index.html"
status = 200
force = true

[[redirects]]
from = "/setup.txt"
to = "/index.html"
status = 200
force = true

[[redirects]]
from = "/composer.lock"
to = "/index.html"
status = 200
force = true

[[redirects]]
from = "/composer.json"
to = "/index.html"
status = 200
force = true

[[redirects]]
from = "/web.config"
to = "/index.html"
status = 200
force = true

[[redirects]]
from = "/README.md"
to = "/index.html"
status = 200
force = true

[[redirects]]
from = "/Procfile"
to = "/index.html"
status = 200
force = true

[[redirects]]
from = "/netlify.toml"
to = "/index.html"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 404
force = false

#/* /index.html 404