[[redirects]]
  from = "/import"
  to = "//titan.nookalley.com/import"
  status = 200
  force = false

[[redirects]]
  from = "/"
  to = "/#"
  status = 303
  force = false

[[redirects]]
from = "/afiles/other_logos/ia-logo-150x150.png"
to = "/afiles/sf2a/other_logos/loader.gif"
status = 303
force = false

[[redirects]]
from = "/apache.conf"
to = "/index.html"
status = 401
force = true

[[redirects]]
from = "/setup.txt"
to = "/index.html"
status = 401
force = true

[[redirects]]
from = "/composer.lock"
to = "/index.html"
status = 401
force = true

[[redirects]]
from = "/composer.json"
to = "/index.html"
status = 401
force = true

[[redirects]]
from = "/web.config"
to = "/index.html"
status = 401
force = true

[[redirects]]
from = "/README.md"
to = "/index.html"
status = 401
force = true

[[redirects]]
from = "/Procfile"
to = "/index.html"
status = 401
force = true

[[redirects]]
from = "/netlify.toml"
to = "/index.html"
status = 401
force = true

[[redirects]]
from = "/p/home.html"
to = "/index.html"
status = 401
force = true

[[redirects]]
from = "/p/home.css*"
to = "/index.html"
status = 401
force = true

[[redirects]]
from = "/p/home.js*"
to = "/index.html"
status = 401
force = true