#[[redirects]]
#  from = "/*"
#  to = "/offline"
#  status = 503
#  force = true
#
#[[redirects]]
#  from = "/*"
#  to = "/cachereset"
#  status = 503
#  force = true

[[redirects]]
  from = "/"
  to = "/#"
  status = 303
  force = false

[[redirects]]
from = "/afiles/other_logos/ia-logo-150x150.png"
to = "/afiles/sf2a/other_logos/loader.gif"
status = 303
force = false

#/* /404.html 404