#[[redirects]]
#  from = "/*"
#  to = "/offline"
#  status = 503
#  force = true
#
#[[redirects]]
#  from = "/*"
#  to = "/cachereset"
#  status = 503
#  force = true

[[redirects]]
  from = "/"
  to = "/#"
  status = 303
  force = true

#/* /404.html 404